In [1]:
pip install pandas

Requirement already satisfied: pandas in c:\users\t0671.tpech\appdata\local\programs\python\python311\lib\site-packages (1.5.3)
Requirement already satisfied: python-dateutil>=2.8.1 in c:\users\t0671.tpech\appdata\roaming\python\python311\site-packages (from pandas) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in c:\users\t0671.tpech\appdata\local\programs\python\python311\lib\site-packages (from pandas) (2022.7.1)
Requirement already satisfied: numpy>=1.21.0 in c:\users\t0671.tpech\appdata\local\programs\python\python311\lib\site-packages (from pandas) (1.24.2)
Requirement already satisfied: six>=1.5 in c:\users\t0671.tpech\appdata\roaming\python\python311\site-packages (from python-dateutil>=2.8.1->pandas) (1.16.0)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip available: 22.3.1 -> 23.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [2]:
import pandas as pd

In [3]:
url="https://data.epa.gov.tw/api/v2/aqx_p_02?api_key=e8dd42e6-9b8b-43f8-991e-b3dee723a52d&limit=1000&sort=datacreationdate%20desc&format=CSV"

In [4]:
df = pd.read_csv(url)
df

   site county  pm25  datacreationdate itemunit
0    大城    彰化縣  53.0  2023-03-02 09:00    μg/m3
1   富貴角    新北市  60.0  2023-03-02 09:00    μg/m3
2    麥寮    雲林縣  49.0  2023-03-02 09:00    μg/m3
3    關山    臺東縣  24.0  2023-03-02 09:00    μg/m3
4    馬公    澎湖縣  63.0  2023-03-02 09:00    μg/m3
..  ...    ...   ...               ...      ...
72   土城    新北市  59.0  2023-03-02 09:00    μg/m3
73   新店    新北市  51.0  2023-03-02 09:00    μg/m3
74   萬里    新北市  67.0  2023-03-02 09:00    μg/m3
75   汐止    新北市  55.0  2023-03-02 09:00    μg/m3
76   基隆    基隆市  64.0  2023-03-02 09:00    μg/m3

[77 rows x 5 columns]

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 77 entries, 0 to 76
Data columns (total 5 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   site              77 non-null     object
 1   county            77 non-null     object
 2   pm25              76 non-null     float64
 3   datacreationdate  77 non-null     object
 4   itemunit          77 non-null     object
dtypes: float64(1), object(4)
memory usage: 3.1+ KB

In [6]:
df = df.dropna()
df

   site county  pm25  datacreationdate itemunit
0    大城    彰化縣  53.0  2023-03-02 09:00    μg/m3
1   富貴角    新北市  60.0  2023-03-02 09:00    μg/m3
2    麥寮    雲林縣  49.0  2023-03-02 09:00    μg/m3
3    關山    臺東縣  24.0  2023-03-02 09:00    μg/m3
4    馬公    澎湖縣  63.0  2023-03-02 09:00    μg/m3
..  ...    ...   ...               ...      ...
72   土城    新北市  59.0  2023-03-02 09:00    μg/m3
73   新店    新北市  51.0  2023-03-02 09:00    μg/m3
74   萬里    新北市  67.0  2023-03-02 09:00    μg/m3
75   汐止    新北市  55.0  2023-03-02 09:00    μg/m3
76   基隆    基隆市  64.0  2023-03-02 09:00    μg/m3

[76 rows x 5 columns]

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 76 entries, 0 to 76
Data columns (total 5 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   site              76 non-null     object
 1   county            76 non-null     object
 2   pm25              76 non-null     float64
 3   datacreationdate  76 non-null     object
 4   itemunit          76 non-null     object
dtypes: float64(1), object(4)
memory usage: 3.6+ KB

In [8]:
df1 = df['site	county	pm25	datacreationdate'.split()]
df1

   site county  pm25  datacreationdate
0    大城    彰化縣  53.0  2023-03-02 09:00
1   富貴角    新北市  60.0  2023-03-02 09:00
2    麥寮    雲林縣  49.0  2023-03-02 09:00
3    關山    臺東縣  24.0  2023-03-02 09:00
4    馬公    澎湖縣  63.0  2023-03-02 09:00
..  ...    ...   ...               ...
72   土城    新北市  59.0  2023-03-02 09:00
73   新店    新北市  51.0  2023-03-02 09:00
74   萬里    新北市  67.0  2023-03-02 09:00
75   汐止    新北市  55.0  2023-03-02 09:00
76   基隆    基隆市  64.0  2023-03-02 09:00

[76 rows x 4 columns]

In [9]:
df1.columns.tolist()

['site', 'county', 'pm25', 'datacreationdate']

In [10]:
df1.values.tolist()

[['大城', '彰化縣', 53.0, '2023-03-02 09:00'],
 ['富貴角', '新北市', 60.0, '2023-03-02 09:00'],
 ['麥寮', '雲林縣', 49.0, '2023-03-02 09:00'],
 ['關山', '臺東縣', 24.0, '2023-03-02 09:00'],
 ['馬公', '澎湖縣', 63.0, '2023-03-02 09:00'],
 ['金門', '金門縣', 78.0, '2023-03-02 09:00'],
 ['埔里', '南投縣', 19.0, '2023-03-02 09:00'],
 ['復興', '高雄市', 43.0, '2023-03-02 09:00'],
 ['永和', '新北市', 59.0, '2023-03-02 09:00'],
 ['竹山', '南投縣', 21.0, '2023-03-02 09:00'],
 ['中壢', '桃園市', 59.0, '2023-03-02 09:00'],
 ['三重', '新北市', 61.0, '2023-03-02 09:00'],
 ['冬山', '宜蘭縣', 37.0, '2023-03-02 09:00'],
 ['宜蘭', '宜蘭縣', 54.0, '2023-03-02 09:00'],
 ['陽明', '臺北市', 56.0, '2023-03-02 09:00'],
 ['花蓮', '花蓮縣', 35.0, '2023-03-02 09:00'],
 ['臺東', '臺東縣', 27.0, '2023-03-02 09:00'],
 ['恆春', '屏東縣', 22.0, '2023-03-02 09:00'],
 ['潮州', '屏東縣', 23.0, '2023-03-02 09:00'],
 ['屏東', '屏東縣', 30.0, '2023-03-02 09:00'],
 ['小港', '高雄市', 37.0, '2023-03-02 09:00'],
 ['前鎮', '高雄市', 40.0, '2023-03-02 09:00'],
 ['前金', '高雄市', 42.0, '2023-03-02 09:00'],
 ['楠梓', '高雄市', 36.0, '2023-03-02 09:00'],
 ['林園', '高雄市', 32.0, '2023-03-02 09:00'],
 ['大寮', '高雄市', 41.0, '2023-03-02 09:00'],
 ['鳳山', '高雄市', 43.0, '2023-03-02 09:00'],
 ['仁武', '高雄市', 45.0, '2023-03-02 09:00'],
 ['橋頭', '高雄市', 41.0, '2023-03-02 09:00'],
 ['美濃', '高雄市', 19.0, '2023-03-02 09:00'],
 ['臺南', '臺南市', 35.0, '2023-03-02 09:00'],
 ['安南', '臺南市', 24.0, '2023-03-02 09:00'],
 ['善化', '臺南市', 32.0, '2023-03-02 09:00'],
 ['新營', '臺南市', 33.0, '2023-03-02 09:00'],
 ['嘉義', '嘉義市', 30.0, '2023-03-02 09:00'],
 ['臺西', '雲林縣', 51.0, '2023-03-02 09:00'],
 ['朴子', '嘉義縣', 45.0, '2023-03-02 09:00'],
 ['新港', '嘉義縣', 42.0, '2023-03-02 09:00'],
 ['崙背', '雲林縣', 45.0, '2023-03-02 09:00'],
 ['斗六', '雲林縣', 35.0, '2023-03-02 09:00'],
 ['南投', '南投縣', 24.0, '2023-03-02 09:00'],
 ['二林', '彰化縣', 45.0, '2023-03-02 09:00'],
 ['線西', '彰化縣', 51.0, '2023-03-02 09:00'],
 ['彰化', '彰化縣', 36.0, '2023-03-02 09:00'],
 ['西屯', '臺中市', 36.0, '2023-03-02 09:00'],
 ['忠明', '臺中市', 37.0, '2023-03-02 09:00'],
 ['大里', '臺中市', 28.0, '2023-03-02 09:00'],
 ['沙鹿', '臺中市', 45.0, '2023-03-02 09:00'],
 ['豐原', '臺中市', 32.0, '2023-03-02 09:00'],
 ['三義', '苗栗縣', 44.0, '2023-03-02 09:00'],
 ['苗栗', '苗栗縣', 50.0, '2023-03-02 09:00'],
 ['頭份', '苗栗縣', 55.0, '2023-03-02 09:00'],
 ['新竹', '新竹市', 62.0, '2023-03-02 09:00'],
 ['竹東', '新竹縣', 53.0, '2023-03-02 09:00'],
 ['湖口', '新竹縣', 62.0, '2023-03-02 09:00'],
 ['龍潭', '桃園市', 53.0, '2023-03-02 09:00'],
 ['平鎮', '桃園市', 56.0, '2023-03-02 09:00'],
 ['觀音', '桃園市', 64.0, '2023-03-02 09:00'],
 ['大園', '桃園市', 62.0, '2023-03-02 09:00'],
 ['桃園', '桃園市', 61.0, '2023-03-02 09:00'],
 ['大同', '臺北市', 62.0, '2023-03-02 09:00'],
 ['松山', '臺北市', 60.0, '2023-03-02 09:00'],
 ['古亭', '臺北市', 61.0, '2023-03-02 09:00'],
 ['萬華', '臺北市', 60.0, '2023-03-02 09:00'],
 ['中山', '臺北市', 59.0, '2023-03-02 09:00'],
 ['士林', '臺北市', 57.0, '2023-03-02 09:00'],
 ['淡水', '新北市', 51.0, '2023-03-02 09:00'],
 ['林口', '新北市', 56.0, '2023-03-02 09:00'],
 ['菜寮', '新北市', 60.0, '2023-03-02 09:00'],
 ['新莊', '新北市', 57.0, '2023-03-02 09:00'],
 ['板橋', '新北市', 55.0, '2023-03-02 09:00'],
 ['土城', '新北市', 59.0, '2023-03-02 09:00'],
 ['新店', '新北市', 51.0, '2023-03-02 09:00'],
 ['萬里', '新北市', 67.0, '2023-03-02 09:00'],
 ['汐止', '新北市', 55.0, '2023-03-02 09:00'],
 ['基隆', '基隆市', 64.0, '2023-03-02 09:00']]

In [11]:

import numpy 
print(numpy.__version__)

1.24.2

In [12]:
import numpy

In [13]:
url = 'https://data.epa.gov.tw/api/v2/aqx_p_02?api_key=e8dd42e6-9b8b-43f8-991e-b3dee723a52d&limit=1000&sort=datacreationdate%20desc&format=CSV'


def get_pm25():
    df = pd.read_csv(url).dropna()['site	county	pm25	datacreationdate'.split()]
    print(df)

    return df.columns.tolist(), df.values.tolist()


get_pm25()

   site county  pm25  datacreationdate
0    大城    彰化縣  53.0  2023-03-02 09:00
1   富貴角    新北市  60.0  2023-03-02 09:00
2    麥寮    雲林縣  49.0  2023-03-02 09:00
3    關山    臺東縣  24.0  2023-03-02 09:00
4    馬公    澎湖縣  63.0  2023-03-02 09:00
..  ...    ...   ...               ...
72   土城    新北市  59.0  2023-03-02 09:00
73   新店    新北市  51.0  2023-03-02 09:00
74   萬里    新北市  67.0  2023-03-02 09:00
75   汐止    新北市  55.0  2023-03-02 09:00
76   基隆    基隆市  64.0  2023-03-02 09:00

[76 rows x 4 columns]

(['site', 'county', 'pm25', 'datacreationdate'],
 [['大城', '彰化縣', 53.0, '2023-03-02 09:00'],
  ['富貴角', '新北市', 60.0, '2023-03-02 09:00'],
  ['麥寮', '雲林縣', 49.0, '2023-03-02 09:00'],
  ['關山', '臺東縣', 24.0, '2023-03-02 09:00'],
  ['馬公', '澎湖縣', 63.0, '2023-03-02 09:00'],
  ['金門', '金門縣', 78.0, '2023-03-02 09:00'],
  ['埔里', '南投縣', 19.0, '2023-03-02 09:00'],
  ['復興', '高雄市', 43.0, '2023-03-02 09:00'],
  ['永和', '新北市', 59.0, '2023-03-02 09:00'],
  ['竹山', '南投縣', 21.0, '2023-03-02 09:00'],
  ['中壢', '桃園市', 59.0, '2023-03-02 09:00'],
  ['三重', '新北市', 61.0, '2023-03-02 09:00'],
  ['冬山', '宜蘭縣', 37.0, '2023-03-02 09:00'],
  ['宜蘭', '宜蘭縣', 54.0, '2023-03-02 09:00'],
  ['陽明', '臺北市', 56.0, '2023-03-02 09:00'],
  ['花蓮', '花蓮縣', 35.0, '2023-03-02 09:00'],
  ['臺東', '臺東縣', 27.0, '2023-03-02 09:00'],
  ['恆春', '屏東縣', 22.0, '2023-03-02 09:00'],
  ['潮州', '屏東縣', 23.0, '2023-03-02 09:00'],
  ['屏東', '屏東縣', 30.0, '2023-03-02 09:00'],
  ['小港', '高雄市', 37.0, '2023-03-02 09:00'],
  ['前鎮', '高雄市', 40.0, '2023-03-02 09:00'],
  ['前金', '高雄市', 42.0, '2023-03-02 09:00'],
  ['楠梓', '高雄市', 36.0, '2023-03-02 09:00'],
  ['林園', '高雄市', 32.0, '2023-03-02 09:00'],
  ['大寮', '高雄市', 41.0, '2023-03-02 09:00'],
  ['鳳山', '高雄市', 43.0, '2023-03-02 09:00'],
  ['仁武', '高雄市', 45.0, '2023-03-02 09:00'],
  ['橋頭', '高雄市', 41.0, '2023-03-02 09:00'],
  ['美濃', '高雄市', 19.0, '2023-03-02 09:00'],
  ['臺南', '臺南市', 35.0, '2023-03-02 09:00'],
  ['安南', '臺南市', 24.0, '2023-03-02 09:00'],
  ['善化', '臺南市', 32.0, '2023-03-02 09:00'],
  ['新營', '臺南市', 33.0, '2023-03-02 09:00'],
  ['嘉義', '嘉義市', 30.0, '2023-03-02 09:00'],
  ['臺西', '雲林縣', 51.0, '2023-03-02 09:00'],
  ['朴子', '嘉義縣', 45.0, '2023-03-02 09:00'],
  ['新港', '嘉義縣', 42.0, '2023-03-02 09:00'],
  ['崙背', '雲林縣', 45.0, '2023-03-02 09:00'],
  ['斗六', '雲林縣', 35.0, '2023-03-02 09:00'],
  ['南投', '南投縣', 24.0, '2023-03-02 09:00'],
  ['二林', '彰化縣', 45.0, '2023-03-02 09:00'],
  ['線西', '彰化縣', 51.0, '2023-03-02 09:00'],
  ['彰化', '彰化縣', 36.0, '2023-03-02 09:00'],
  ['西屯', '臺中市', 36.0, '2023-03-02 09:00'],
  ['忠明', '臺中市', 37.0, '2023-03-02 09:00'],
  ['大里', '臺中市', 28.0, '2023-03-02 09:00'],
  ['沙鹿', '臺中市', 45.0, '2023-03-02 09:00'],
  ['豐原', '臺中市', 32.0, '2023-03-02 09:00'],
  ['三義', '苗栗縣', 44.0, '2023-03-02 09:00'],
  ['苗栗', '苗栗縣', 50.0, '2023-03-02 09:00'],
  ['頭份', '苗栗縣', 55.0, '2023-03-02 09:00'],
  ['新竹', '新竹市', 62.0, '2023-03-02 09:00'],
  ['竹東', '新竹縣', 53.0, '2023-03-02 09:00'],
  ['湖口', '新竹縣', 62.0, '2023-03-02 09:00'],
  ['龍潭', '桃園市', 53.0, '2023-03-02 09:00'],
  ['平鎮', '桃園市', 56.0, '2023-03-02 09:00'],
  ['觀音', '桃園市', 64.0, '2023-03-02 09:00'],
  ['大園', '桃園市', 62.0, '2023-03-02 09:00'],
  ['桃園', '桃園市', 61.0, '2023-03-02 09:00'],
  ['大同', '臺北市', 62.0, '2023-03-02 09:00'],
  ['松山', '臺北市', 60.0, '2023-03-02 09:00'],
  ['古亭', '臺北市', 61.0, '2023-03-02 09:00'],
  ['萬華', '臺北市', 60.0, '2023-03-02 09:00'],
  ['中山', '臺北市', 59.0, '2023-03-02 09:00'],
  ['士林', '臺北市', 57.0, '2023-03-02 09:00'],
  ['淡水', '新北市', 51.0, '2023-03-02 09:00'],
  ['林口', '新北市', 56.0, '2023-03-02 09:00'],
  ['菜寮', '新北市', 60.0, '2023-03-02 09:00'],
  ['新莊', '新北市', 57.0, '2023-03-02 09:00'],
  ['板橋', '新北市', 55.0, '2023-03-02 09:00'],
  ['土城', '新北市', 59.0, '2023-03-02 09:00'],
  ['新店', '新北市', 51.0, '2023-03-02 09:00'],
  ['萬里', '新北市', 67.0, '2023-03-02 09:00'],
  ['汐止', '新北市', 55.0, '2023-03-02 09:00'],
  ['基隆', '基隆市', 64.0, '2023-03-02 09:00']])

### 取得六都平均值

In [14]:
round(df.groupby('county').get_group('新北市')['pm25'])

1     60.0
8     59.0
11    61.0
67    51.0
68    56.0
69    60.0
70    57.0
71    55.0
72    59.0
73    51.0
74    67.0
75    55.0
Name: pm25, dtype: float64

In [15]:
df

   site county  pm25  datacreationdate itemunit
0    大城    彰化縣  53.0  2023-03-02 09:00    μg/m3
1   富貴角    新北市  60.0  2023-03-02 09:00    μg/m3
2    麥寮    雲林縣  49.0  2023-03-02 09:00    μg/m3
3    關山    臺東縣  24.0  2023-03-02 09:00    μg/m3
4    馬公    澎湖縣  63.0  2023-03-02 09:00    μg/m3
..  ...    ...   ...               ...      ...
72   土城    新北市  59.0  2023-03-02 09:00    μg/m3
73   新店    新北市  51.0  2023-03-02 09:00    μg/m3
74   萬里    新北市  67.0  2023-03-02 09:00    μg/m3
75   汐止    新北市  55.0  2023-03-02 09:00    μg/m3
76   基隆    基隆市  64.0  2023-03-02 09:00    μg/m3

[76 rows x 5 columns]

In [16]:
round(df.groupby('county').get_group('新北市')['pm25'].mean(),2)

57.58

In [17]:
set(df['county'])

{'南投縣',
 '嘉義市',
 '嘉義縣',
 '基隆市',
 '宜蘭縣',
 '屏東縣',
 '彰化縣',
 '新北市',
 '新竹市',
 '新竹縣',
 '桃園市',
 '澎湖縣',
 '臺中市',
 '臺北市',
 '臺南市',
 '臺東縣',
 '花蓮縣',
 '苗栗縣',
 '金門縣',
 '雲林縣',
 '高雄市'}

In [30]:
six_countys = ['臺北市','新北市','桃園市','臺中市','臺南市','高雄市']

datas=[]
for county in six_countys:
    pm25 = round(df.groupby('county').get_group(county)['pm25'].mean(),2)
    datas.append([county,pm25])

datas

[['臺北市', 59.29],
 ['新北市', 57.58],
 ['桃園市', 59.17],
 ['臺中市', 35.6],
 ['臺南市', 31.0],
 ['高雄市', 38.09]]

### 取得不同縣市

In [21]:
countys=list(set(df['county']))
countys

['高雄市',
 '嘉義市',
 '基隆市',
 '新北市',
 '宜蘭縣',
 '嘉義縣',
 '屏東縣',
 '花蓮縣',
 '雲林縣',
 '彰化縣',
 '澎湖縣',
 '苗栗縣',
 '臺東縣',
 '臺中市',
 '新竹縣',
 '金門縣',
 '桃園市',
 '臺南市',
 '南投縣',
 '新竹市',
 '臺北市']

In [28]:
df.groupby('county').get_group(countys[0])

   site county  pm25  datacreationdate itemunit
7    復興    高雄市  43.0  2023-03-02 09:00    μg/m3
20   小港    高雄市  37.0  2023-03-02 09:00    μg/m3
21   前鎮    高雄市  40.0  2023-03-02 09:00    μg/m3
22   前金    高雄市  42.0  2023-03-02 09:00    μg/m3
24   楠梓    高雄市  36.0  2023-03-02 09:00    μg/m3
25   林園    高雄市  32.0  2023-03-02 09:00    μg/m3
26   大寮    高雄市  41.0  2023-03-02 09:00    μg/m3
27   鳳山    高雄市  43.0  2023-03-02 09:00    μg/m3
28   仁武    高雄市  45.0  2023-03-02 09:00    μg/m3
29   橋頭    高雄市  41.0  2023-03-02 09:00    μg/m3
30   美濃    高雄市  19.0  2023-03-02 09:00    μg/m3

In [29]:
countys

['高雄市',
 '嘉義市',
 '基隆市',
 '新北市',
 '宜蘭縣',
 '嘉義縣',
 '屏東縣',
 '花蓮縣',
 '雲林縣',
 '彰化縣',
 '澎湖縣',
 '苗栗縣',
 '臺東縣',
 '臺中市',
 '新竹縣',
 '金門縣',
 '桃園市',
 '臺南市',
 '南投縣',
 '新竹市',
 '臺北市']